module.exports = [
    [
        "class ShoppingList extends React.Component {",
        "render() {",
        "return (",
        "<div className='shopping-list'>",
        "<h1>Shopping List for {this.props.name}</h1>",
        "<ul>",
        "<li>Instagram</li>",
        "</ul>",
        "</div>",
        ");",
        "}}"
    ],
    [
        "<link rel='stylesheet' href='style.css'/>",
        "</head>",
        "<body>",
        "<h1 id='main'>Welcome to Jamstack</h1>",
        "<p class='mt-5'>It's pretty cool</p>",
        "</body>",
        "</html>"
    ],
    [
        '<script>',
        '$( "button" ).click(function() {',
        '$( "p" ).empty();',
        '});',
        '</script>',
    ],
    [
        '<!doctype html>',
        '<html lang="en">',
        '<head>',
        '<meta charset="utf-8">',
        '<title>Jamstack Attack!</title>',
        '<script src="app.js"></script>',
        '</head>',
    ],
    [
        "const Counter = {",
        "data() {",
        "return {",
        "counter: 0",
        "}}}",
        "Vue.createApp(Counter).mount('#counter')",
    ],
    [
        "methods: {",
        "reverseMessage() {",
        "this.message = this.message",
        ".split('')",
        ".reverse()",
        ".join('')",
        "}}",
    ],
    [
        "const TodoList = {",
        "data() {",
        "return {",
        "groceryList: [",
        "{ id: 0, text: 'Vegetables' },",
        "{ id: 1, text: 'Cheese' },",
        "{ id: 2, text: 'Gunpowder...?' }",
        "]",
        "}}}",
    ],
    [
        '$.ajax({',
        'url: "/api/getWeather",',
        'data: {',
        'zipcode: 97201',
        '},',
        'success: function( result ) {',
        '$( "#weather-temp" ).html( "<strong>" + result + "</strong> degrees" );',
        '}',
        '});',
    ],
    [
        'var hiddenBox = $( "#banner-message" );',
        '$( "#button-container button" ).on( "click", function( event ) {',
        'hiddenBox.show();',
        '});',
    ],
    [
        '<h2>Products</h2>',
        '<div *ngFor="let product of products">',
        '<h3>',
        "<a [title]=\"product.name + ' details'\">",
        '{{ product.name }}',
        '</a>',
        '</h3>',
        '</div>',
    ],
    [
        "const TableHeader = () => {",
        "return (",
        "<thead>",
        "<tr>",
        "<th>Name</th>",
        "<th>Job</th>",
        "</tr>",
        "</thead>",
        ")",
        "}",
    ],
    [
        "const TableBody = (props) => {",
        "const rows = props.characterData.map((row, index) => {",
        "return (",
        "<tr key={index}>",
        "<td>{row.name}</td>",
        "<td>{row.job}</td>",
        "</tr>",
        ")",
        "})",
        "return <tbody>{rows}</tbody>",
        "}",
    ],
    [
        "removeCharacter = (index) => {",
        "const {characters} = this.state",
        "this.setState({",
        "characters: characters.filter((character, i) => {",
        "return i !== index",
        "}),",
        "})",
        "}",
    ],
    [
        "handleChange = (event) => {",
        "const {name, value} = event.target",
        "this.setState({",
        "[name]: value,",
        "})",
        "}",
    ],
    [
        "fetch(url)",
        ".then((result) => result.json())",
        ".then((result) => {",
        "this.setState({",
        "data: result,",
        "})})",
    ],
    [
        "render() {",
        "const {data} = this.state",
        "const result = data.map((entry, index) => {",
        "return <li key={index}>{entry}</li>",
        "})",
        "return <ul>{result}</ul>",
        "}",
    ],
    [
        "function NumberList(props) {",
        "const numbers = props.numbers;",
        "const listItems = numbers.map((number) => {",
        "<li>{number}</li>",
        "});",
        "return (",
        "<ul>{listItems}</ul>",
        ");",
        "}",
    ]
]