module.exports = [
    [
        "class ShoppingList extends React.Component {",
        "render() {",
        "return (",
        "<div className='shopping-list'>",
        "<h1>Shopping List for {this.props.name}</h1>",
        "<ul>",
        "<li>Instagram</li>",
        "</ul>",
        "</div>",
        ");",
        "}}"
    ],
    [
        "<link rel='stylesheet' href='style.css'/>",
        "</head>",
        "<body>",
        "<h1 id='main'>Welcome to Jamstack</h1>",
        "<p class='mt-5'>It's pretty cool</p>",
        "</body>",
        "</html>"
    ],
    [
        '<script>',
        '$( "button" ).click(function() {',
        '$( "p" ).empty();',
        '});',
        '</script>',
    ],
    [
        '<!doctype html>',
        '<html lang="en">',
        '<head>',
        '<meta charset="utf-8">',
        '<title>Jamstack Attack!</title>',
        '<script src="app.js"></script>',
        '</head>',
    ],
    [
        "const Counter = {",
        "data() {",
        "return {",
        "counter: 0",
        "}}}",
        "Vue.createApp(Counter).mount('#counter')",
    ],
    [
        "methods: {",
        "reverseMessage() {",
        "this.message = this.message",
        ".split('')",
        ".reverse()",
        ".join('')",
        "}}",
    ],
    [
        "const TodoList = {",
        "data() {",
        "return {",
        "groceryList: [",
        "{ id: 0, text: 'Vegetables' },",
        "{ id: 1, text: 'Cheese' },",
        "{ id: 2, text: 'Gunpowder...?' }",
        "]",
        "}}}",
    ],
    [
        '$.ajax({',
        'url: "/api/getWeather",',
        'data: {',
        'zipcode: 97201',
        '},',
        'success: function( result ) {',
        '$( "#weather-temp" ).html( "<strong>" + result + "</strong> degrees" );',
        '}',
        '});',
    ],
    [
        'var hiddenBox = $( "#banner-message" );',
        '$( "#button-container button" ).on( "click", function( event ) {',
        'hiddenBox.show();',
        '});',
    ],
    [
        '<h2>Products</h2>',
        '<div *ngFor="let product of products">',
        '<h3>',
        "<a [title]=\"product.name + ' details'\">",
        '{{ product.name }}',
        '</a>',
        '</h3>',
        '</div>',
    ],
    [
        "const TableHeader = () => {",
        "return (",
        "<thead>",
        "<tr>",
        "<th>Name</th>",
        "<th>Job</th>",
        "</tr>",
        "</thead>",
        ")",
        "}",
    ],
    [
        "const TableBody = (props) => {",
        "const rows = props.characterData.map((row, index) => {",
        "return (",
        "<tr key={index}>",
        "<td>{row.name}</td>",
        "<td>{row.job}</td>",
        "</tr>",
        ")",
        "})",
        "return <tbody>{rows}</tbody>",
        "}",
    ],
    [
        "removeCharacter = (index) => {",
        "const {characters} = this.state",
        "this.setState({",
        "characters: characters.filter((character, i) => {",
        "return i !== index",
        "}),",
        "})",
        "}",
    ],
    [
        "handleChange = (event) => {",
        "const {name, value} = event.target",
        "this.setState({",
        "[name]: value,",
        "})",
        "}",
    ],
    [
        "fetch(url)",
        ".then((result) => result.json())",
        ".then((result) => {",
        "this.setState({",
        "data: result,",
        "})})",
    ],
    [
        "render() {",
        "const {data} = this.state",
        "const result = data.map((entry, index) => {",
        "return <li key={index}>{entry}</li>",
        "})",
        "return <ul>{result}</ul>",
        "}",
    ],
    [
        "function NumberList(props) {",
        "const numbers = props.numbers;",
        "const listItems = numbers.map((number) => {",
        "<li>{number}</li>",
        "});",
        "return (",
        "<ul>{listItems}</ul>",
        ");",
        "}",
    ],
    [
        "function reduce(arr, fn, init) {",
        "let output;",
        "arr.forEach(i => {",
        "output = fn(output, i);",
        "})",
        "return output",
        "}"
    ],
    [
        "function intersection(...args) {",
        "function fn(accumulator, current) {",
        "let output = [];",
        "current.forEach(i => {",
        "if (accumulator.indexOf(i) >= 0) {",
        "output.push(i); }})",
        "return output; }",
        "return reduce(args.slice(1), fn, args[0]); }",
        "intersection([1,2,3], [1, 2], [2, 7]); // -> [ 2 ]"
    ],
    [
        "<h2>Contact us</h2>",
        "<form action='script.php' method='POST'>",
        "<fieldset>",
        "<legend>General information</legend>",
        "<label for='name'>Name</label>",
        "<input type='text' id='name' />",
        "</fieldset>",
        "</form>"
    ],
    [
        "<ul>",
        "<li>",
        "Instructions",
        "<ol>",
        "<li>Do this</li>",
        "<li>Then that</li>",
        "<li>Lastly, do this</li>",
        "</ol>",
        "</li>",
        "</ul>"
    ],
    [
        "<nav>",
        "<ul>",
        "<li>",
        "<a href='/'>Home</a></li>",
        "<li><a href='about.html'>About us",
        "</a></li>",
        "<li>",
        "<a href='contact.html'>Contact us</a>",
        "</li>",
        "</ul>",
        "</nav>"
    ],
    [
        "<dl>",
        "<div>",
        "<dt>",
        "Term",
        "</dt>",
        "<dd>",
        "Description",
        "</dd>",
        "</div>",
        "</dl>"
    ],
    [
        "/**",
        "Use a better box model (opinionated).",
        "*/",
        "*,",
        "*::before,",
        "*::after {",
        "box-sizing: border-box;",
        "}"
    ],
    [
        "<table>",
        "<caption>Awesome caption</caption>",
        "<colgroup span='4'></colgroup>",
        "<thead>",
        "<tr><th colspan='2'>",
        "The table header</th>",
        "</tr></thead>",
        "<tbody>",
        "<tr>",
        "<td>The table body</td>",
        "<td>with two columns</td>",
        "</tr></tbody></table>"
    ],
    [
        "<header>",
        "<nav>",
        "</nav>",
        "</header>",
        "<main>",
        "<article>",
        "</article>",
        "</main>",
        "<aside>",
        "</aside>",
        "<footer>",
        "</footer>"
    ],
    [
        '<label for="bully">How do you stack up?</label>',
        '<select name="bully" multiple size="4">',
        '<optgroup label="Order of Operations">',
        '<option value="worst">First the worst</option>',
        '<option value="best">Second the best</option>',
        '<option value="nerd" disabled>Third the nerd</option>',
        '</optgroup>',
        '</select>'
    ],
    [
        "function isPrime(n){",
        "var divisor = 2;",
        "while (n > divisor){",
        "if(n % divisor == 0){",
        "return false; ",
        "} else {",
        "divisor++; } ",
        "}",
        "return true; }"
    ],
    [
        "function fibonacci(n){",
        "if(n<=1)",
        "return n;",
        "else",
        "return fibonacci(n-1) + fibonacci (n-2);",
        "}",
    ],
    [
        "function greatestCommonDivisor(a, b){",
        "if(b == 0)",
        "return a;",
        "else ",
        "return greatestCommonDivisor(b, a%b);",
        "}",
    ],
    [
        "function reverseInPlace(str){",
        "return str.split(' ')",
        ".reverse()",
        ".join(' ')",
        ".split('')",
        ".reverse()",
        ".join('');",
        "}"
    ]
]