module.exports = [
    [
        "class ShoppingList extends React.Component {",
        "render() {",
        "return (",
        "<div className='shopping-list'>",
        "<h1>Shopping List for {this.props.name}</h1>",
        "<ul>",
        "<li>Instagram</li>",
        "</ul>",
        "</div>",
        ");",
        "}}"
    ],
    [
        "<link rel='stylesheet' href='style.css'/>",
        "</head>",
        "<body>",
        "<h1 id='main'>Welcome to Jamstack</h1>",
        "<p class='mt-5'>It's pretty cool</p>",
        "</body>",
        "</html>"
    ],
    [
        '<script>',
        '$( "button" ).click(function() {',
        '$( "p" ).empty();',
        '});',
        '</script>',
    ],
    [
        '<!doctype html>',
        '<html lang="en">',
        '<head>',
        '<meta charset="utf-8">',
        '<title>Jamstack Attack!</title>',
        '<script src="app.js"></script>',
        '</head>',
    ],
    [
        "const Counter = {",
        "data() {",
        "return {",
        "counter: 0",
        "}}}",
        "Vue.createApp(Counter).mount('#counter')",
    ],
    [
        "methods: {",
        "reverseMessage() {",
        "this.message = this.message",
        ".split('')",
        ".reverse()",
        ".join('')",
        "}}",
    ],
    [
        "const TodoList = {",
        "data() {",
        "return {",
        "groceryList: [",
        "{ id: 0, text: 'Vegetables' },",
        "{ id: 1, text: 'Cheese' },",
        "{ id: 2, text: 'Gunpowder...?' }",
        "]",
        "}}}",
    ],
    [
        '$.ajax({',
        'url: "/api/getWeather",',
        'data: {',
        'zipcode: 97201',
        '},',
        'success: function( result ) {',
        '$( "#weather-temp" ).html( "<strong>" + result + "</strong> degrees" );',
        '}',
        '});',
    ],
    [
        'var hiddenBox = $( "#banner-message" );',
        '$( "#button-container button" ).on( "click", function( event ) {',
        'hiddenBox.show();',
        '});',
    ],
    [
        '<h2>Products</h2>',
        '<div *ngFor="let product of products">',
        '<h3>',
        "<a [title]=\"product.name + ' details'\">",
        '{{ product.name }}',
        '</a>',
        '</h3>',
        '</div>',
    ]
]