module.exports = [
    "ReactDOM.render(<App />, document.getElementById('root'));",
    "const headers = ['Band', 'Singer', 'Inception', 'Label'];",
    "font-size: calc(1rem + 0.5vw);",
    "@media (max-width: 400px) {",
    "border: 2px solid #000;",
    "tr:first-of-type th:not(:last-child) {",
    "padding: 0.125rem 0.5rem;",
    "import { mergeOptions } from '../util/index'",
    "if (typeof plugin.install === 'function') {",
    "plugin.apply(null, args)",
    '<html lang="en-US">',
    '<meta name="robots" content="index, follow" />',
    "var disableStr = 'ga-disable-UA-42425022-1';",
    'padding: 10px 20px 15px;',
    '.dark-line {border-color: #d2d2d2 !important;}',
    'const x = 2;',
    '{ "name": "Robert", "creator": true }',
    'function sum(x,y) { return x + y; }',  
    'font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;',
    '.form-group.required .control-label:after {',
    '<p><strong>Learning and Knowledge</strong></p>',
    '<!-- .mega-menu__section -->',
    '<section class="mega-menu__section" aria-labelledby="Other">',
    '<li class="sub-menu__item">',
    '<div class="col-sm-4">',
    '<label for="form-contact-lastname">Last Name</label>',
    'id="form-contact-lastname" type="text" name="lastname"',
    '<h2 class="whiteh2" style="padding-right:5px;">',
    '<a class="btn btn-primary" href="https://rmion.com">',
    'data-tweet-limit="1" data-theme="dark"',
    '<span class="fa fa-question-circle" aria-hidden="true">',
    "var navId = buttonEl.getAttribute('aria-controls');",
    'buttonEl.setAttribute("aria-expanded", "false");',
    "navLinks[a].setAttribute('aria-current','true');",
    'for (var b = 0; b < navItems.length; b++) {',
    "a=o.getElementsByTagName('head')[0];",
    '<meta charset="utf-8" />',
    "import ReactDOM from 'react-dom'",
    "<Form handleSubmit={this.handleSubmit} />",
    '<input type="button" value="Submit" onClick={this.sendForm} />',
    "const citrusFruits = ['orange', 'lime', 'mandarin']",
    "const doubled = numbers.map((number) => number * 2);",
    "let newLength = fruits.unshift('Strawberry')",
    "console.log(arr[arr.length - 1])",
    "console.log(years['2'] != years['02'])",
    "alert( arr.concat([3, 4], [5, 6]) );",
    "arr.forEach(function(item, index, array) {",
    "let user = users.find(item => item.id == 1);",
    "const doubleList = list => list.map(x => x * 2);",
    "setTimeout(() => resolve(value), 3000);",
    "const fetchDataQuickly = async time => {",
    '<td id="mp-right" class="MainPageBG mp-bordered">',
    '<footer id="footer" class="mw-footer" role="contentinfo" >',
    '<form action="/w/index.php" id="searchform">',
    "let x, y = 20;",
    "let [a, b, c] = [5, 8, 12];",
    "let result = marks >= 30 ? 'Pass' : 'Fail';",
    "let imagePath = getImagePath() || 'default.jpg';",
    "[x, y] = [y, x];",
    "const add = (num1, num2) => num1 + num2;",
    "console.log(`Missed call from ${number} at ${time}`);",
    "if ([1, 'one', 2, 'two'].includes(value)) {",
    "let average = +'42.6';",
    "'sorry\n'.repeat(100);",
    "const arr = [2, 8, 15, 4]; Math.max(...arr);",
    "for (const val of arr) { console.log(val); }",
    "let arr2 = [...arr1, 60, 80];",
    "const cloneObj = JSON.parse(JSON.stringify(obj));",
    "let obj = {x: 20, y: 'hello'}; const cloneObj = {...obj};",
    "console.error('Error found');",
    "console.table({a: 1, b: 2, c: 3});",
    "for(let i=0; i<3; i++){ console.count(i); }",
    "console.log('%cI am a styled log', styles);",
]