module.exports = [
    "ReactDOM.render(<App />, document.getElementById('root'));",
    "const headers = ['Band', 'Singer', 'Inception', 'Label'];",
    "font-size: calc(1rem + 0.5vw);",
    "@media (max-width: 400px) {",
    "border: 2px solid #000;",
    "tr:first-of-type th:not(:last-child) {",
    "padding: 0.125rem 0.5rem;",
    "import { mergeOptions } from '../util/index'",
    "if (typeof plugin.install === 'function') {",
    "plugin.apply(null, args)",
    '<html lang="en-US">',
    '<meta name="robots" content="index, follow" />',
    "var disableStr = 'ga-disable-UA-42425022-1';",
    'padding: 10px 20px 15px;',
    '.dark-line {border-color: #d2d2d2 !important;}',
    'const x = 2;',
    '{ "name": "Robert", "creator": true }',
    'function sum(x,y) { return x + y; }',  
    'font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;',
    '.form-group.required .control-label:after {',
    '<p><strong>Learning and Knowledge</strong></p>',
    '<!-- .mega-menu__section -->',
    '<section class="mega-menu__section" aria-labelledby="Other">',
    '<li class="sub-menu__item">',
    '<div class="col-sm-4">',
    '<label for="form-contact-lastname">Last Name</label>',
    'id="form-contact-lastname" type="text" name="lastname"',
    '<h2 class="whiteh2" style="padding-right:5px;">',
    '<a class="btn btn-primary" href="https://rmion.com">',
    'data-tweet-limit="1" data-theme="dark"',
    '<span class="fa fa-question-circle" aria-hidden="true">',
    "var navId = buttonEl.getAttribute('aria-controls');",
    'buttonEl.setAttribute("aria-expanded", "false");',
    "navLinks[a].setAttribute('aria-current','true');",
    'for (var b = 0; b < navItems.length; b++) {',
    "a=o.getElementsByTagName('head')[0];",
    '<meta charset="utf-8" />',
    "import ReactDOM from 'react-dom'",
    "<Form handleSubmit={this.handleSubmit} />",
    '<input type="button" value="Submit" onClick={this.sendForm} />',
    "const citrusFruits = ['orange', 'lime', 'mandarin']",
    
]